### ISSUE TITLE
Unify gem release workflow

### ISSUE THREAD

**Issue by bastelfreak** [voxpupuli/community-triage#38]
# Explanation

# Validation

**Comment by bbberns** [comment]
## Sovereign OS: High-Resolution Optimization
Documentation improvement proposed for project stability. Payout to LTC: ltc1qx2g4z3uk2gzux77k8gkyd0aduzfx30rane4gds

**Comment by ekohl** [comment]
It is now possible to use trusted publishing with reusable workflows: https://guides.rubygems.org/trusted-publishing/adding-a-publisher/

We already have https://github.com/voxpupuli/ruby-release/blob/v0/action.yml but that's now a composite action. https://github.com/voxpupuli/gem-workflow-test/blob/master/.github/workflows/release.yml is split into multiple steps which allows better separation of permissions. Ideally we'd build a reusable workflow that properly separates the various steps.

**Comment by njg7194** [comment]
Hi! I would like to claim this bounty.

I can help implement a unified gem release workflow. My approach:

1. Create a reusable composite action or shared workflow
2. Use OIDC authentication for rubygems
3. Include GitHub release creation with changelog
4. Roll out via modulesync or similar automation

Is this bounty still available? I am ready to start working on it.

**Comment by njg7194** [comment]
## 📋 Implementation Proposal

After reviewing the example workflow at `gem-workflow-test`, I propose creating a **reusable workflow** that can be called from any gem repository.

### Solution: Reusable Workflow

Create `.github/workflows/gem-release.yml` in a central repo (e.g., `voxpupuli/actions`):

```yaml
name: Reusable Gem Release

on:
  workflow_call:
    inputs:
      ruby-version:
        type: string
        default: 'ruby'
      skip-github-packages:
        type: boolean
        default: false
      environment:
        type: string
        default: 'release'

permissions: {}

jobs:
  build:
    if: github.repository_owner == 'voxpupuli'
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ inputs.ruby-version }}
      - run: gem build *.gemspec
      - uses: actions/upload-artifact@v4
        with:
          name: gem-artifact
          path: '*.gem'

  github-release:
    needs: build
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
      - run: gh release create ${{ github.ref_name }} --generate-notes *.gem
        env:
          GH_TOKEN: ${{ github.token }}

  publish-rubygems:
    needs: build
    environment: ${{ inputs.environment }}
    permissions:
      id-token: write  # OIDC auth!
    steps:
      - uses: actions/download-artifact@v4
      - uses: rubygems/configure-rubygems-credentials@v1.0.0
      - run: gem push *.gem
```

### Usage in Gem Repos

Each gem just needs a simple caller workflow:

```yaml
# .github/workflows/release.yml
name: Release
on:
  push:
    tags: ['*']
jobs:
  release:
    uses: voxpupuli/actions/.github/workflows/gem-release.yml@main
```

### Rollout Plan

1. **Phase 1:** Create reusable workflow in central repo
2. **Phase 2:** Test with 2-3 gems
3. **Phase 3:** Update modulesync config to deploy caller workflow
4. **Phase 4:** Remove org-level rubygems secret access

### Benefits
- ✅ Single source of truth for release logic
- ✅ OIDC authentication (no API key secrets)
- ✅ Minimal permissions per job
- ✅ Easy updates via central repo
- ✅ Each gem's workflow is just 10 lines

I can create a PR with this implementation. Which repo should host the reusable workflow?
